// ADS Sports Eyewear — site backend (dependency-free Node HTTP).
// Handles: JV partner form, SEO guide-page lead form, public per-page CTA config,
// and the God admin backend — CTA swap (per-page / bulk / global default),
// product add/edit/delete, and holding-content editing. Content/product edits are
// persisted as JSON and the static pages are regenerated by build/generate.js.
// nginx proxies /api/ here. Core CRM + Zapmail email via medigap.plus.
const http = require("http");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execFile } = require("child_process");

const PORT = process.env.PORT || 3120;
const CORE_BASE = process.env.CORE_API_BASE || "https://medigap.plus";
const CORE_KEY = process.env.CORE_KEY || "";
const CORE_SECRET = process.env.CORE_SECRET || "";
const OWNER_EMAIL = process.env.OWNER_EMAIL || "jeff.cline@me.com";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "AdsGod!2026";
const ADMIN_SECRET = process.env.ADMIN_SECRET || crypto.createHash("sha256").update("ads-cta-" + ADMIN_PASSWORD).digest("hex");

const BUILD_DIR = path.join(__dirname, "..", "build");
const CONTENT_DIR = path.join(BUILD_DIR, "content");
const SITE_DIR = path.join(__dirname, "..", "site");
const CTA_FILE = path.join(__dirname, "cta-config.json");
const PRODUCTS_RUNTIME = path.join(BUILD_DIR, "products.runtime.json");
const GENERATOR = path.join(BUILD_DIR, "generate.js");
const DEFAULT_CTA_HREF = "https://el.ag/prescription-sunglasses";

const esc = (s) => String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const clip = (s, n) => String(s == null ? "" : s).slice(0, n);
const readJSON = (f, fb) => { try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch { return fb; } };
const safeKey = (k) => /^[a-z0-9-]+$/i.test(String(k || ""));

/* ---- CTA config (seeded with the global default on first run) -------------- */
function loadCta() {
  let c = readJSON(CTA_FILE, null);
  if (!c) { c = { __default__: { enabled: true, href: DEFAULT_CTA_HREF, label: "Shop Prescription Sunglasses", note: "", newtab: true, type: "affiliate" } }; saveCta(c); }
  return c;
}
function saveCta(obj) { fs.writeFileSync(CTA_FILE, JSON.stringify(obj, null, 2)); }
function ctaFor(page) {
  const all = loadCta();
  const pick = (all[page] && all[page].enabled && all[page].href) ? all[page]
    : (all.__default__ && all.__default__.enabled && all.__default__.href) ? all.__default__ : null;
  return pick ? { href: pick.href, label: pick.label || "", note: pick.note || "", newtab: pick.newtab !== false } : {};
}

/* ---- Admin auth (stateless HMAC token) ------------------------------------- */
const adminToken = () => crypto.createHmac("sha256", ADMIN_SECRET).update("god:v1").digest("hex");
function checkAuth(req) {
  const tok = (req.headers["authorization"] || "").replace(/^Bearer\s+/i, "").trim();
  const want = adminToken();
  if (!tok || tok.length !== want.length) return false;
  try { return crypto.timingSafeEqual(Buffer.from(tok), Buffer.from(want)); } catch { return false; }
}

/* ---- Products store (seed manifest + runtime overrides) --------------------- */
function seedProducts() { try { return require(path.join(BUILD_DIR, "products.config.js")).PRODUCTS; } catch { return []; } }
function runtimeProducts() { return readJSON(PRODUCTS_RUNTIME, []); }
function allProducts() {
  const byId = new Map(seedProducts().map((p) => [String(p.id), Object.assign({ source: "seed" }, p)]));
  for (const p of runtimeProducts()) {
    if (!p || !p.id) continue;
    if (p.deleted) byId.delete(String(p.id));
    else byId.set(String(p.id), Object.assign({ source: "runtime" }, byId.get(String(p.id)) || {}, p));
  }
  return [...byId.values()];
}
function upsertRuntimeProduct(p) {
  const rt = runtimeProducts().filter((x) => String(x.id) !== String(p.id));
  rt.push(p);
  fs.writeFileSync(PRODUCTS_RUNTIME, JSON.stringify(rt, null, 2));
}

/* ---- Regenerate static pages (build/generate.js) --------------------------- */
let regenBusy = false, regenQueued = false;
function regenerate() {
  return new Promise((resolve) => {
    if (regenBusy) { regenQueued = true; return resolve({ ok: true, queued: true }); }
    regenBusy = true;
    execFile(process.execPath, [GENERATOR], { cwd: BUILD_DIR, timeout: 60000 }, (err, so, se) => {
      regenBusy = false;
      if (regenQueued) { regenQueued = false; regenerate(); }
      if (err) { console.error("regen error:", se || err.message); return resolve({ ok: false, error: String(se || err.message).slice(0, 400) }); }
      resolve({ ok: true });
    });
  });
}

/* ---- Core CRM + email ------------------------------------------------------ */
function coreHeaders() { return (CORE_KEY && CORE_SECRET) ? { "x-core-key": CORE_KEY, "x-core-secret": CORE_SECRET, "content-type": "application/json" } : null; }
async function coreLead(lead) { const h = coreHeaders(); if (!h) return false; try { const r = await fetch(`${CORE_BASE}/api/core/lead`, { method: "POST", headers: h, body: JSON.stringify(lead), signal: AbortSignal.timeout(9000) }); return r.ok; } catch { return false; } }
async function coreEmail(to, subject, html) { const h = coreHeaders(); if (!h) return false; try { const r = await fetch(`${CORE_BASE}/api/core/email`, { method: "POST", headers: h, body: JSON.stringify({ to, subject, html, provider: "zapmail" }), signal: AbortSignal.timeout(15000) }); const j = await r.json().catch(() => ({})); return !!(r.ok && (j.ok === undefined || j.ok)); } catch { return false; } }

function readBody(req, max = 200000) {
  return new Promise((resolve) => { let b = ""; req.on("data", (c) => { b += c; if (b.length > max) req.destroy(); }); req.on("end", () => { try { resolve(JSON.parse(b || "{}")); } catch { resolve(null); } }); });
}

/* Normalize a CTA config object from admin input. */
function ctaObj(d) {
  const type = ["affiliate", "order", "email"].includes(d.type) ? d.type : "affiliate";
  let href = clip(d.href, 500).trim();
  if (type === "email" && href && !/^mailto:/i.test(href)) href = "mailto:" + href;
  return { enabled: !!href && d.enabled !== false, type, href, label: clip(d.label, 80).trim(), note: clip(d.note, 160).trim(), newtab: type !== "email" && d.newtab !== false, updated: new Date().toISOString() };
}

const server = http.createServer(async (req, res) => {
  const send = (code, obj) => { res.writeHead(code, { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*", "Cache-Control": "no-store" }); res.end(JSON.stringify(obj)); };
  if (req.method === "OPTIONS") { res.writeHead(204, { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Content-Type,Authorization", "Access-Control-Allow-Methods": "GET,POST,OPTIONS" }); return res.end(); }
  const u = new URL(req.url, "http://x");
  const url = u.pathname.replace(/\/+$/, "") || "/";
  const auth = () => checkAuth(req);

  if (req.method === "GET" && (url === "/api/partner/health" || url === "/health")) return send(200, { ok: true, service: "ads", ts: Date.now() });

  /* -- Public: per-page CTA (falls back to global default) -- */
  if (req.method === "GET" && url === "/api/cta") return send(200, ctaFor(u.searchParams.get("p") || ""));

  /* -- Admin: login -- */
  if (req.method === "POST" && url === "/api/admin/login") {
    const d = await readBody(req) || {};
    if (clip(d.password, 200) === ADMIN_PASSWORD) return send(200, { ok: true, token: adminToken() });
    return send(401, { error: "Incorrect password." });
  }

  /* -- Admin: read everything the console needs -- */
  if (req.method === "GET" && url === "/api/admin/cta") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    let pages = [];
    try { const { PAGES, CLUSTERS } = require(path.join(BUILD_DIR, "pages.config.js")); pages = PAGES.map((p) => ({ path: p.path, nav: p.nav, cluster: CLUSTERS[p.cluster].title, kind: "guide", key: p.key })); } catch {}
    const prods = allProducts().map((p) => ({ path: p.path || `/product/${String(p.name || "").replace(/[^A-Za-z0-9]+/g, "-")}/${p.id}`, nav: p.name, cluster: p.category || "Products", kind: "product", id: p.id }));
    return send(200, { ok: true, config: loadCta(), pages, products: prods });
  }

  /* -- Admin: set/clear CTA for one page, many pages (bulk), or the global default -- */
  if (req.method === "POST" && url === "/api/admin/cta") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    const d = await readBody(req) || {};
    const targets = Array.isArray(d.pages) && d.pages.length ? d.pages : (d.page ? [d.page] : []);
    if (!targets.length) return send(400, { error: "No target page(s)." });
    const all = loadCta();
    for (const t of targets) {
      const key = clip(t, 300).trim(); if (!key) continue;
      if (d.clear) delete all[key];
      else all[key] = ctaObj(d);
    }
    saveCta(all);
    return send(200, { ok: true, config: all });
  }

  /* -- Admin: list products -- */
  if (req.method === "GET" && url === "/api/admin/products") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    return send(200, { ok: true, products: allProducts() });
  }

  /* -- Admin: add / edit a product (holding page) -- */
  if (req.method === "POST" && url === "/api/admin/products") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    const d = await readBody(req) || {};
    const name = clip(d.name, 160).trim();
    if (!name) return send(400, { error: "Product name is required." });
    let id = clip(d.id, 40).trim();
    if (!id) id = "g" + crypto.randomBytes(4).toString("hex"); // new God product
    const nameSlug = name.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const prod = {
      id, name, brand: clip(d.brand, 60).trim() || "ADS",
      category: clip(d.category, 80).trim() || "Sport Eyewear",
      primaryKw: clip(d.primaryKw, 120).trim() || name,
      description: clip(d.description, 6000),
      heroImg: clip(d.heroImg, 120).trim() || "sunglasses-hero.jpg",
      features: Array.isArray(d.features) ? d.features.map((f) => clip(f, 160)).filter(Boolean) : (typeof d.features === "string" ? d.features.split(/\n/).map((s) => s.trim()).filter(Boolean) : []),
      faq: Array.isArray(d.faq) ? d.faq.filter((f) => f && f.q && f.a).map((f) => ({ q: clip(f.q, 200), a: clip(f.a, 1000) })) : [],
      path: `/product/${nameSlug}/${id}`, out: `product/${nameSlug}/${id}.html`,
      updated: new Date().toISOString(),
    };
    upsertRuntimeProduct(prod);
    const r = await regenerate();
    return send(r.ok ? 200 : 500, r.ok ? { ok: true, product: prod } : { error: "Saved, but regenerate failed: " + r.error, product: prod });
  }

  /* -- Admin: delete a God-added product -- */
  if (req.method === "POST" && url === "/api/admin/products/delete") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    const d = await readBody(req) || {};
    const id = clip(d.id, 40).trim(); if (!id) return send(400, { error: "Missing id." });
    const existing = allProducts().find((p) => String(p.id) === id);
    upsertRuntimeProduct({ id, deleted: true });
    if (existing && existing.out) { try { fs.unlinkSync(path.join(SITE_DIR, existing.out)); } catch {} }
    const r = await regenerate();
    return send(200, { ok: true, regen: r.ok });
  }

  /* -- Admin: read guide holding content for editing -- */
  if (req.method === "GET" && url === "/api/admin/content") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    const key = u.searchParams.get("key") || "";
    if (!safeKey(key)) return send(400, { error: "Bad key." });
    const f = path.join(CONTENT_DIR, key + ".json");
    if (!fs.existsSync(f)) return send(404, { error: "Not found." });
    return send(200, { ok: true, key, content: readJSON(f, {}) });
  }

  /* -- Admin: save guide holding content -> regenerate -- */
  if (req.method === "POST" && url === "/api/admin/content") {
    if (!auth()) return send(401, { error: "Unauthorized" });
    const d = await readBody(req) || {};
    if (!safeKey(d.key)) return send(400, { error: "Bad key." });
    if (!d.content || typeof d.content !== "object") return send(400, { error: "Missing content object." });
    const f = path.join(CONTENT_DIR, d.key + ".json");
    if (!fs.existsSync(f)) return send(404, { error: "Unknown page." });
    fs.writeFileSync(f, JSON.stringify(d.content, null, 2));
    const r = await regenerate();
    return send(r.ok ? 200 : 500, r.ok ? { ok: true } : { error: "Saved, but regenerate failed: " + r.error });
  }

  /* -- Public: SEO guide-page lead form -- */
  if (req.method === "POST" && url === "/api/lead") {
    const d = await readBody(req);
    if (!d) return send(400, { error: "Bad request" });
    const first = clip(d.firstName, 80).trim(), last = clip(d.lastName, 80).trim(), phone = clip(d.phone, 40).trim();
    const city = clip(d.city, 80).trim(), state = clip(d.state, 30).trim(), zip = clip(d.zip, 12).trim();
    const page = clip(d.page, 300).trim(), keyword = clip(d.keyword, 160).trim(), pageTitle = clip(d.pageTitle, 200).trim();
    if (!first || !last || !phone) return send(400, { error: "Please add your first name, last name and phone number." });
    const name = `${first} ${last}`.trim();
    const loc = [city, state, zip].filter(Boolean).join(", ");
    const notes = [`ADS Sports Eyewear — guide-page info request`, `Interest / keyword: ${keyword || "—"}`, `Page: ${pageTitle || page}`, `URL: https://adseyewear.com${page}`, `Location: ${loc || "—"}`].join("\n");
    send(200, { ok: true });
    const html = `<div style="font-family:Arial,sans-serif;font-size:15px;color:#111"><h2 style="color:#ea5a1e;margin:0 0 8px">New adseyewear.com lead 🕶️</h2><table cellpadding="6" style="border-collapse:collapse"><tr><td><b>Name</b></td><td>${esc(name)}</td></tr><tr><td><b>Phone</b></td><td>${esc(phone)}</td></tr><tr><td><b>Location</b></td><td>${esc(loc) || "—"}</td></tr><tr><td><b>Interest / keyword</b></td><td>${esc(keyword) || "—"}</td></tr><tr><td><b>Page</b></td><td>${esc(pageTitle || page)}</td></tr></table><p><a href="https://adseyewear.com${esc(page)}">https://adseyewear.com${esc(page)}</a></p></div>`;
    coreLead({ name, phone, notes, creatorRef: "adseyewear-seo", source: `adseyewear:${keyword || page}` }).catch(() => {});
    coreEmail(OWNER_EMAIL, `🕶️ adseyewear lead: ${name} — "${keyword || page}"`, html).catch(() => {});
    return;
  }

  /* -- Existing: JV partner application -- */
  if (req.method === "POST" && url === "/api/partner") {
    const d = await readBody(req);
    if (!d) return send(400, { error: "Bad request" });
    const first = clip(d.firstName, 80).trim(), last = clip(d.lastName, 80).trim(), phone = clip(d.phone, 40).trim(), email = clip(d.email, 160).trim();
    const city = clip(d.city, 80), state = clip(d.state, 30), zip = clip(d.zip, 12);
    const businesses = clip(d.businesses, 300), businessName = clip(d.businessName, 160), pitch = clip(d.pitch, 4000);
    if (!first || !last || !phone || !pitch) return send(400, { error: "Missing required fields." });
    const name = `${first} ${last}`.trim();
    const loc = [city, state, zip].filter(Boolean).join(", ");
    const notes = [`ADS Sports Eyewear — Operating Partner Application`, `Location: ${loc || "—"}`, `Businesses owned: ${businesses || "—"}`, `Business name: ${businessName || "—"}`, `Why a great partner: ${pitch}`].join("\n");
    send(200, { ok: true });
    const html = `<div style="font-family:Arial,sans-serif;font-size:15px;color:#111"><h2 style="color:#ea5a1e;margin:0 0 8px">New ADS Eyewear partner application</h2><table cellpadding="6" style="border-collapse:collapse"><tr><td><b>Name</b></td><td>${esc(name)}</td></tr><tr><td><b>Phone</b></td><td>${esc(phone)}</td></tr><tr><td><b>Email</b></td><td>${esc(email) || "—"}</td></tr><tr><td><b>Location</b></td><td>${esc(loc) || "—"}</td></tr></table><p style="white-space:pre-wrap;background:#f6f4ef;padding:12px;border-radius:8px">${esc(pitch)}</p></div>`;
    coreLead({ name, email, phone, notes, creatorRef: "adseyewear-partner" }).catch(() => {});
    coreEmail(OWNER_EMAIL, `🕶️ New ADS Eyewear partner: ${name} (${phone})`, html).catch(() => {});
    return;
  }

  return send(404, { error: "Not found" });
});
loadCta(); // seed default CTA on boot
server.listen(PORT, "127.0.0.1", () => console.log(`ADS site service on :${PORT} (build=${fs.existsSync(GENERATOR) ? "ok" : "MISSING"})`));
